// ignore_for_file: library_private_types_in_public_api, type_alias_equality
// This file is generated by script; do not edit manually.
// Generation command: dart run scripts/generate_provider_registry.dart
//
// Provider registry (auto-generated)
// Scans all Riverpod provider definitions under lib/ and re-exports them
// aggregated, for easier dependency tracking.
//
// Note: the following same-named providers are defined in multiple files; only
// the first occurrence is kept here and the other definitions are not exported.
// Duplicates at the source level are an architectural hazard and are tracked
// in the refactor backlog.
//   tokenizerServiceProvider: package:kirakira/presentation/providers/settings_providers.dart / package:kirakira/presentation/providers/tokenizer_providers.dart
//   worldInfoRepositoryProvider: package:kirakira/data/repositories/world_info_repository.dart / package:kirakira/presentation/providers/world_info_providers.dart

// 1 provider(s)
export 'package:kirakira/core/services/initialization_service.dart' show
    databaseProvider;

// 1 provider(s)
export 'package:kirakira/data/repositories/bookmark_repository.dart' show
    bookmarkRepositoryProvider;

// 1 provider(s)
export 'package:kirakira/data/repositories/character_repository.dart' show
    characterRepositoryProvider;

// 1 provider(s)
export 'package:kirakira/data/repositories/chat_repository.dart' show
    chatRepositoryProvider;

// 1 provider(s)
export 'package:kirakira/data/repositories/group_repository.dart' show
    groupRepositoryProvider;

// 1 provider(s)
export 'package:kirakira/data/repositories/persona_repository.dart' show
    personaRepositoryProvider;

// 1 provider(s)
export 'package:kirakira/data/repositories/world_info_repository.dart' show
    worldInfoRepositoryProvider;

// 3 provider(s)
export 'package:kirakira/domain/services/debug_log_service.dart' show
    debugLogServiceProvider,
    logEntriesStreamProvider,
    currentLogsProvider;

// 1 provider(s)
export 'package:kirakira/domain/services/slash_command_service.dart' show
    slashCommandServiceProvider;

// 1 provider(s)
export 'package:kirakira/presentation/providers/advanced_mode_provider.dart' show
    advancedModeProvider;

// 5 provider(s)
export 'package:kirakira/presentation/providers/ai_preset_providers.dart' show
    aiCustomPresetsProvider,
    allAIPresetsProvider,
    activeAIPresetIdProvider,
    activeAIPresetProvider,
    aiPresetManagerProvider;

// 1 provider(s)
export 'package:kirakira/presentation/providers/announcement_provider.dart' show
    pendingAnnouncementProvider;

// 4 provider(s)
export 'package:kirakira/presentation/providers/background_providers.dart' show
    globalBackgroundProvider,
    characterBackgroundProvider,
    effectiveBackgroundProvider,
    savedCharacterBackgroundsProvider;

// 1 provider(s)
export 'package:kirakira/presentation/providers/big_dipper_providers.dart' show
    bigDipperProvider;

// 3 provider(s)
export 'package:kirakira/presentation/providers/bookmark_providers.dart' show
    chatBookmarksProvider,
    bookmarkProvider,
    bookmarkNotifierProvider;

// 5 provider(s)
export 'package:kirakira/presentation/providers/cfg_scale_providers.dart' show
    cfgScaleSettingsProvider,
    chatCFGSettingsProvider,
    effectiveCFGSettingsProvider,
    isCFGActiveProvider,
    cfgGuidanceScaleDisplayProvider;

// 6 provider(s)
export 'package:kirakira/presentation/providers/character_filter_providers.dart' show
    characterFilterProvider,
    allLegacyTagsProvider,
    allCombinedTagsProvider,
    filteredCharactersProvider,
    favoriteCharactersProvider,
    tagCountsProvider;

// 3 provider(s)
export 'package:kirakira/presentation/providers/character_providers.dart' show
    selectedCharacterIdProvider,
    selectedCharacterProvider,
    characterSearchProvider;

// 5 provider(s)
export 'package:kirakira/presentation/providers/chat_providers.dart' show
    activeChatIdProvider,
    activeChatProvider,
    characterChatsProvider,
    allChatsProvider,
    recentChatsProvider;

// 4 provider(s)
export 'package:kirakira/presentation/providers/context_usage_providers.dart' show
    contextUsageServiceProvider,
    matchedWorldInfoEntriesProvider,
    contextUsageProvider,
    detailedContextUsageProvider;

// 5 provider(s)
export 'package:kirakira/presentation/providers/fingerprint_providers.dart' show
    judgeConfigIdProvider,
    judgeModelProvider,
    judgeModelsProvider,
    fingerprintServiceProvider,
    fingerprintProvider;

// 5 provider(s)
export 'package:kirakira/presentation/providers/group_providers.dart' show
    allGroupsProvider,
    groupProvider,
    groupListProvider,
    activeGroupIdProvider,
    selectedGroupCharacterIdProvider;

// 1 provider(s)
export 'package:kirakira/presentation/providers/home_background_providers.dart' show
    homeBackgroundProvider;

// 1 provider(s)
export 'package:kirakira/presentation/providers/home_music_providers.dart' show
    homeMusicProvider;

// 1 provider(s)
export 'package:kirakira/presentation/providers/home_music_service.dart' show
    homeMusicServiceProvider;

// 12 provider(s)
export 'package:kirakira/presentation/providers/image_gen_providers.dart' show
    imageGenServiceProvider,
    imageGenSettingsProvider,
    imageGenStateProvider,
    generateImageProvider,
    parseImagineCommandProvider,
    extractImageUrlsProvider,
    downloadImageProvider,
    defaultModelsProvider,
    fetchedModelsProvider,
    availableModelsProvider,
    modelDisplayNameProvider,
    supportsFetchingModelsProvider;

// 4 provider(s)
export 'package:kirakira/presentation/providers/instruct_providers.dart' show
    activeInstructTemplateIdProvider,
    activeInstructTemplateProvider,
    allInstructTemplatesProvider,
    instructFormatterProvider;

// 2 provider(s)
export 'package:kirakira/presentation/providers/llm_configs_provider.dart' show
    llmConfigRepositoryProvider,
    llmConfigsProvider;

// 1 provider(s)
export 'package:kirakira/presentation/providers/locale_provider.dart' show
    localeProvider;

// 5 provider(s)
export 'package:kirakira/presentation/providers/logit_bias_providers.dart' show
    logitBiasServiceProvider,
    logitBiasSettingsProvider,
    activeLogitBiasEntriesProvider,
    isLogitBiasActiveProvider,
    logitBiasValidationProvider;

// 7 provider(s)
export 'package:kirakira/presentation/providers/logprobs_providers.dart' show
    logprobsSettingsProvider,
    messageLogprobsProvider,
    selectedTokenLogprobProvider,
    messageLogprobProvider,
    hasLogprobsProvider,
    logprobsParserProvider,
    probabilityColorProvider;

// 4 provider(s)
export 'package:kirakira/presentation/providers/macro_providers.dart' show
    macroContextProvider,
    macroServiceProvider,
    macroProcessorProvider,
    processTextWithMacrosProvider;

// 1 provider(s)
export 'package:kirakira/presentation/providers/mvu_settings_providers.dart' show
    mvuSettingsProvider;

// 5 provider(s)
export 'package:kirakira/presentation/providers/persona_providers.dart' show
    allPersonasProvider,
    activePersonaIdProvider,
    activePersonaProvider,
    personaForCharacterProvider,
    personaNotifierProvider;

// 7 provider(s)
export 'package:kirakira/presentation/providers/prompt_manager_providers.dart' show
    promptManagerProvider,
    enabledPromptSectionsProvider,
    isSectionEnabledProvider,
    customPresetsProvider,
    allPresetsProvider,
    activePresetIdProvider,
    activePresetProvider;

// 2 provider(s)
export 'package:kirakira/presentation/providers/quote_color_providers.dart' show
    quoteColorStateProvider,
    quoteColorProvider;

// 6 provider(s)
export 'package:kirakira/presentation/providers/regex_providers.dart' show
    regexServiceProvider,
    globalRegexScriptsProvider,
    characterRegexScriptsProvider,
    combinedRegexScriptsProvider,
    regexScriptsReadyProvider,
    regexSettingsProvider;

// 10 provider(s)
export 'package:kirakira/presentation/providers/settings_providers.dart' show
    sharedPreferencesProvider,
    llmServiceProvider,
    ejsRenderRegistryProvider,
    llmConfigProvider,
    appSettingsProvider,
    connectionTestProvider,
    modelFetchProvider,
    tokenizerServiceProvider,
    chatSummarizationServiceProvider,
    connectionMetricsProvider;

// 9 provider(s)
export 'package:kirakira/presentation/providers/sprite_providers.dart' show
    emotionDetectionServiceProvider,
    spriteServiceProvider,
    spriteSettingsProvider,
    spritePackProvider,
    hasSpritesProvider,
    messageSpriteProvider,
    spritePackNotifierProvider,
    detectedEmotionProvider,
    detectedEmotionWithConfidenceProvider;

// 3 provider(s)
export 'package:kirakira/presentation/providers/statistics_providers.dart' show
    appStatisticsProvider,
    computedChatStatisticsProvider,
    statisticsSummaryProvider;

// 10 provider(s)
export 'package:kirakira/presentation/providers/stt_providers.dart' show
    sttServiceProvider,
    sttSettingsProvider,
    sttListeningProvider,
    sttResultProvider,
    sttAvailableProvider,
    sttStartListeningProvider,
    sttStopListeningProvider,
    sttToggleListeningProvider,
    sttCancelListeningProvider,
    sttClearResultProvider;

// 7 provider(s)
export 'package:kirakira/presentation/providers/tag_providers.dart' show
    tagRepositoryProvider,
    allTagsProvider,
    tagUsageCountsProvider,
    characterTagsProvider,
    tagNotifierProvider,
    tagFilterProvider,
    tagFilteredCharacterIdsProvider;

// 6 provider(s)
export 'package:kirakira/presentation/providers/theme_providers.dart' show
    activeThemeIdProvider,
    customThemesProvider,
    allThemesProvider,
    activeThemeConfigProvider,
    activeThemeDataProvider,
    isDarkModeProvider;

// 5 provider(s)
export 'package:kirakira/presentation/providers/tokenizer_providers.dart' show
    tokenizerSettingsProvider,
    tokenizationResultProvider,
    tokenCountEstimateProvider,
    tokenStatisticsProvider,
    bestTokenizerProvider;

// 6 provider(s)
export 'package:kirakira/presentation/providers/translation_providers.dart' show
    translationServiceProvider,
    translationSettingsProvider,
    translateTextProvider,
    detectLanguageProvider,
    translateProvider,
    translationStateProvider;

// 7 provider(s)
export 'package:kirakira/presentation/providers/tts_providers.dart' show
    ttsServiceProvider,
    ttsSettingsProvider,
    characterVoiceSettingsProvider,
    ttsSpeakingProvider,
    availableVoicesProvider,
    ttsSpeakProvider,
    ttsStopProvider;

// 5 provider(s)
export 'package:kirakira/presentation/providers/variables_providers.dart' show
    variablesServiceProvider,
    globalVariablesProvider,
    localVariablesProvider,
    allVariablesInfoProvider,
    variableCountProvider;

// 9 provider(s)
export 'package:kirakira/presentation/providers/vector_storage_providers.dart' show
    vectorStorageServiceProvider,
    embeddingServiceProvider,
    vectorStorageSettingsProvider,
    vectorCollectionsProvider,
    activeCollectionProvider,
    collectionStatisticsProvider,
    vectorSearchProvider,
    textChunkerProvider,
    isRAGActiveProvider;

// 6 provider(s)
export 'package:kirakira/presentation/providers/world_info_providers.dart' show
    allWorldInfosProvider,
    globalWorldInfosProvider,
    characterWorldInfosProvider,
    activeWorldInfoIdsProvider,
    worldInfoNotifierProvider,
    worldInfoMatcherProvider;

// 1 provider(s)
export 'package:kirakira/presentation/router/app_router.dart' show
    appRouterProvider;

// 1 provider(s)
export 'package:kirakira/presentation/screens/ai_config/ai_config_screen.dart' show
    isChinaRegionProvider;

// 1 provider(s)
export 'package:kirakira/presentation/providers/chat_export_provider.dart' show
    chatExportServiceProvider;

// 3 provider(s)
export 'package:kirakira/presentation/screens/import/import_screen.dart' show
    importServiceProvider,
    urlImportServiceProvider,
    importStateProvider;

// 1 provider(s)
export 'package:kirakira/presentation/widgets/chat/extracted_images_widget.dart' show
    hasExtractableImagesProvider;

/// Statistics (auto-generated by script)
const int kTotalProviders = 209;
const String kRegistryGeneratedAt = '2026-08-20';
