import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:kirakira/presentation/theme/design_tokens.dart';
import 'package:kirakira/presentation/theme/glass_theme_extension.dart';

/// App theme: dual themes following the iOS design spec.
///
/// Dark: near-black base, three-level gray hierarchy, translucent white text,
/// zero shadows.
/// Light: iOS grouped gray background contrasting white cards.
class AppTheme {
  // Brand colors
  static const Color primaryColor = DesignTokens.primary; // primary accent
  static const Color secondaryColor = DesignTokens.secondary; // gradients/charts second series
  static const Color accentColor = DesignTokens.accent; // teal, positive state/data highlight only

  // Dark palette (direct token pass-through)
  static const Color darkBackground = DesignTokens.darkBackground;
  static const Color darkSurface = DesignTokens.darkSurface;
  static const Color darkCard = DesignTokens.darkCard;

  // Text colors
  // Canonical aliases (new code must use these)
  static const Color darkTextPrimary = DesignTokens.darkTextPrimary;
  static const Color darkTextSecondary = DesignTokens.darkTextSecondary;
  static const Color darkTextTertiary = DesignTokens.darkTextTertiary;
  static const Color darkTextDisabled = DesignTokens.darkTextDisabled;
  static const Color lightTextPrimary = DesignTokens.lightTextPrimary;
  static const Color lightTextSecondary = DesignTokens.lightTextSecondary;
  static const Color lightTextTertiary = DesignTokens.lightTextTertiary;
  static const Color lightTextDisabled = DesignTokens.lightTextDisabled;
  static const Color lightSurface = DesignTokens.lightSurface;
  static const Color lightCard = DesignTokens.lightCard;

  // Legacy chat-domain compatibility layer (screens/chat and widgets/chat
  // still reference these; do not migrate that layer here):
  // Old alias names kept, values now point to the iOS tokens.
  // Do not use in new code; use darkTextXxx above.
  static const Color textPrimary = DesignTokens.darkTextPrimary;
  static const Color textSecondary = DesignTokens.darkTextSecondary;
  static const Color textMuted = DesignTokens.darkTextTertiary;
  static const Color darkDivider = DesignTokens.darkSeparator;

  // Chat bubbles (tokens assigned here; chat rendering layer must not change them)
  static const Color userBubble = DesignTokens.userBubble;
  static const Color assistantBubble = DesignTokens.assistantBubble;
  static const Color systemBubble = DesignTokens.systemBubble;

  // textTheme construction (full scale, both variants generated by one method)
  static TextTheme _textTheme({
    required Color primary,
    required Color secondary,
    required Color tertiary,
  }) {
    return TextTheme(
      // Large Title 34/Bold (SliverAppBar.large)
      displayLarge: TextStyle(
        color: primary,
        fontSize: DesignTokens.fontSizeDisplayLarge,
        fontWeight: FontWeight.bold,
        letterSpacing: 0.4,
      ),
      displayMedium: const TextStyle(
        fontSize: DesignTokens.fontSize3xl,
        fontWeight: FontWeight.bold,
      ).copyWith(color: primary),
      displaySmall: const TextStyle(
        fontSize: DesignTokens.fontSize2xl,
        fontWeight: FontWeight.bold,
      ).copyWith(color: primary),
      headlineLarge: const TextStyle(
        fontSize: DesignTokens.fontSize3xl,
        fontWeight: FontWeight.bold,
      ).copyWith(color: primary), // Title 1 28
      headlineMedium: const TextStyle(
        fontSize: DesignTokens.fontSize2xl,
        fontWeight: FontWeight.bold,
      ).copyWith(color: primary), // Title 2 22
      headlineSmall: const TextStyle(
        fontSize: DesignTokens.fontSizeXl,
        fontWeight: FontWeight.w600,
      ).copyWith(color: primary), // Title 3 20
      titleLarge: const TextStyle(
        fontSize: DesignTokens.fontSizeXl,
        fontWeight: FontWeight.w600,
      ).copyWith(color: primary), // Title 3
      titleMedium: const TextStyle(
        fontSize: DesignTokens.fontSizeHeadline,
        fontWeight: FontWeight.w600,
      ).copyWith(color: primary), // Headline 17 (list row title)
      titleSmall: TextStyle(
        color: secondary,
        fontSize: DesignTokens.fontSizeSm,
        fontWeight: FontWeight.w600,
        letterSpacing: 0.5,
      ), // inset-grouped section header small text
      bodyLarge: TextStyle(
        color: primary,
        fontSize: DesignTokens.fontSizeBodyLarge,
      ), // Body 17
      bodyMedium: TextStyle(
        color: secondary,
        fontSize: DesignTokens.fontSizeBodyMedium,
      ), // Subheadline 15 (secondary description)
      bodySmall: TextStyle(
        color: tertiary,
        fontSize: DesignTokens.fontSizeXs,
      ), // Caption 1 12
      labelLarge: const TextStyle(
        fontSize: DesignTokens.fontSizeHeadline,
        fontWeight: FontWeight.w600,
      ).copyWith(color: primary), // button label
      labelMedium: TextStyle(
        color: secondary,
        fontSize: DesignTokens.fontSizeSm,
        fontWeight: FontWeight.w500,
      ),
      labelSmall: TextStyle(
        color: tertiary,
        fontSize: DesignTokens.fontSizeCaption,
        fontWeight: FontWeight.w500,
      ),
    );
  }

  // Dark theme (primary)
  static ThemeData get darkTheme {
    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.dark,
      extensions: const [GlassThemeExtension()],
      // Global ripple removed: press feedback is provided by KiraPressable
      splashFactory: NoSplash.splashFactory,
      highlightColor: Colors.transparent,
      colorScheme: const ColorScheme.dark(
        primary: primaryColor,
        secondary: secondaryColor,
        tertiary: accentColor,
        surface: darkSurface,
        surfaceContainerHighest: darkCard, // level 3: input/control fill
        onPrimary: Colors.white,
        onSecondary: Colors.white,
        outlineVariant: DesignTokens.darkSeparator,
      ),
      scaffoldBackgroundColor: darkBackground,
      cardColor: darkSurface, // inset-grouped card background (level 2)
      dividerColor: DesignTokens.darkSeparator,
      dividerTheme: const DividerThemeData(
        color: DesignTokens.darkSeparator,
        thickness: 0.5,
        space: 0.5,
      ),
      // AppBar: page-colored background, no scroll tint, left-aligned,
      // collapsed title 17/w600
      appBarTheme: const AppBarTheme(
        backgroundColor: darkBackground,
        foregroundColor: darkTextPrimary,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        scrolledUnderElevation: 0,
        centerTitle: false,
        titleTextStyle: TextStyle(
          color: darkTextPrimary,
          fontSize: DesignTokens.fontSizeHeadline,
          fontWeight: FontWeight.w600,
        ),
      ),
      cardTheme: CardThemeData(
        color: darkSurface,
        elevation: 0, // dark theme: zero shadow by design
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusCard),
        ),
      ),
      dialogTheme: DialogThemeData(
        backgroundColor: darkSurface,
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusDialog),
        ),
        titleTextStyle: const TextStyle(
          color: darkTextPrimary,
          fontSize: DesignTokens.fontSizeHeadline,
          fontWeight: FontWeight.w600,
        ),
      ),
      listTileTheme: const ListTileThemeData(
        textColor: darkTextPrimary,
        iconColor: darkTextSecondary,
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: darkCard,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusInput),
          borderSide:
              const BorderSide(color: DesignTokens.darkSeparator, width: 0.5),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusInput),
          borderSide:
              const BorderSide(color: DesignTokens.darkSeparator, width: 0.5),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusInput),
          borderSide: const BorderSide(color: primaryColor, width: 2),
        ),
        hintStyle: const TextStyle(color: darkTextTertiary),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: primaryColor,
          foregroundColor: Colors.white,
          padding: const EdgeInsets.symmetric(
              horizontal: DesignTokens.spaceLg, vertical: DesignTokens.spaceSm),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(DesignTokens.radiusInput),
          ),
        ),
      ),
      floatingActionButtonTheme: const FloatingActionButtonThemeData(
        backgroundColor: primaryColor,
        foregroundColor: Colors.white,
      ),
      bottomNavigationBarTheme: const BottomNavigationBarThemeData(
        backgroundColor: darkSurface,
        selectedItemColor: primaryColor,
        unselectedItemColor: darkTextTertiary,
      ),
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: darkSurface,
        indicatorColor: primaryColor.withValues(alpha: 0.2),
        labelTextStyle: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) {
            return const TextStyle(
                color: primaryColor, fontSize: DesignTokens.fontSizeXs);
          }
          return const TextStyle(
              color: darkTextTertiary, fontSize: DesignTokens.fontSizeXs);
        }),
      ),
      // Let CupertinoSwitch etc. default to the primary color
      cupertinoOverrideTheme: const CupertinoThemeData(
        brightness: Brightness.dark,
        primaryColor: primaryColor,
      ),
      textTheme: _textTheme(
        primary: DesignTokens.darkTextPrimary,
        secondary: DesignTokens.darkTextSecondary,
        tertiary: DesignTokens.darkTextTertiary,
      ),
    );
  }

  // Light theme
  static ThemeData get lightTheme {
    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.light,
      extensions: const [GlassThemeExtension()],
      splashFactory: NoSplash.splashFactory,
      highlightColor: Colors.transparent,
      colorScheme: const ColorScheme.light(
        primary: primaryColor,
        secondary: secondaryColor,
        tertiary: accentColor,
        surface: lightSurface,
        surfaceContainerHighest: DesignTokens.lightFillTertiary,
        onPrimary: Colors.white,
        onSecondary: Colors.white,
        outlineVariant: DesignTokens.lightSeparator,
      ),
      scaffoldBackgroundColor: DesignTokens.lightBackground,
      cardColor: DesignTokens.lightCard,
      dividerColor: DesignTokens.lightSeparator,
      dividerTheme: const DividerThemeData(
        color: DesignTokens.lightSeparator,
        thickness: 0.5,
        space: 0.5,
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: DesignTokens.lightBackground,
        foregroundColor: lightTextPrimary,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        scrolledUnderElevation: 0,
        centerTitle: false,
        titleTextStyle: TextStyle(
          color: lightTextPrimary,
          fontSize: DesignTokens.fontSizeHeadline,
          fontWeight: FontWeight.w600,
        ),
      ),
      cardTheme: CardThemeData(
        color: DesignTokens.lightCard,
        elevation: 0, // light cards rely on gray background contrast, no elevation
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusCard),
        ),
      ),
      dialogTheme: DialogThemeData(
        backgroundColor: lightSurface,
        elevation: 6, // light theme: shadow allowed only for modal/sheet
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusDialog),
        ),
        titleTextStyle: const TextStyle(
          color: lightTextPrimary,
          fontSize: DesignTokens.fontSizeHeadline,
          fontWeight: FontWeight.w600,
        ),
      ),
      listTileTheme: const ListTileThemeData(
        textColor: lightTextPrimary,
        iconColor: lightTextSecondary,
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: DesignTokens.lightFillTertiary,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusInput),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusInput),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusInput),
          borderSide: const BorderSide(color: primaryColor, width: 2),
        ),
        hintStyle: const TextStyle(color: lightTextTertiary),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: primaryColor,
          foregroundColor: Colors.white,
          padding: const EdgeInsets.symmetric(
              horizontal: DesignTokens.spaceLg, vertical: DesignTokens.spaceSm),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(DesignTokens.radiusInput),
          ),
        ),
      ),
      floatingActionButtonTheme: const FloatingActionButtonThemeData(
        backgroundColor: primaryColor,
        foregroundColor: Colors.white,
      ),
      bottomNavigationBarTheme: const BottomNavigationBarThemeData(
        backgroundColor: DesignTokens.lightSurface,
        selectedItemColor: primaryColor,
        unselectedItemColor: lightTextTertiary,
      ),
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: DesignTokens.lightSurface,
        indicatorColor: primaryColor.withValues(alpha: 0.15),
        labelTextStyle: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) {
            return const TextStyle(
                color: primaryColor, fontSize: DesignTokens.fontSizeXs);
          }
          return const TextStyle(
              color: lightTextTertiary, fontSize: DesignTokens.fontSizeXs);
        }),
      ),
      cupertinoOverrideTheme: const CupertinoThemeData(
        brightness: Brightness.light,
        primaryColor: primaryColor,
      ),
      textTheme: _textTheme(
        primary: DesignTokens.lightTextPrimary,
        secondary: DesignTokens.lightTextSecondary,
        tertiary: DesignTokens.lightTextTertiary,
      ),
    );
  }
}
