import 'dart:convert';
import 'package:kirakira/data/models/mvu_settings.dart';

/// 共享 TavernHelper 门面(酒馆助手环境注入脚本)。
///
/// 来源:照 webview_chat_stage.dart 中已验证能跑的注入脚本誊抄,
/// 剔除消息气泡专用的高度上报逻辑,frameId 参数化,宏值改由宿主注入。
/// 消息 iframe 与全局脚本引擎房共用此门面。
///
/// [frameId] 每个 iframe 的唯一标识,用于 __thCall 请求路由。
/// 宿主须在加载前往 window 注入 __KIRA_MACRO_VALUES({user,char})。
String buildTavernHelperFacadeJs({
  required String frameId,
  required MvuSettings mvu,
}) {
  return '(function(){'
      // ── localStorage / sessionStorage polyfill(老 WebView 兜底) ──
      'var _s={};try{localStorage.getItem("__t");}catch(e){'
      'try{Object.defineProperty(window,"localStorage",{configurable:true,value:{'
      'getItem:function(k){return _s[k]||null;},'
      'setItem:function(k,v){_s[k]=String(v);},'
      'removeItem:function(k){delete _s[k];},'
      'clear:function(){_s={};},'
      'key:function(i){return Object.keys(_s)[i]||null;},'
      'get length(){return Object.keys(_s).length;}'
      '}});parent.postMessage({__thLog:true,text:"[polyfill] localStorage 覆盖成功"},"*");}'
      'catch(e2){parent.postMessage({__thLog:true,text:"[polyfill] localStorage 覆盖失败: "+e2},"*");}'
      '}'
      'var _ss={};try{sessionStorage.getItem("__t");}catch(e){'
      'try{Object.defineProperty(window,"sessionStorage",{configurable:true,value:{'
      'getItem:function(k){return _ss[k]||null;},'
      'setItem:function(k,v){_ss[k]=String(v);},'
      'removeItem:function(k){delete _ss[k];},'
      'clear:function(){_ss={};},'
      'key:function(i){return Object.keys(_ss)[i]||null;},'
      'get length(){return Object.keys(_ss).length;}'
      '}});parent.postMessage({__thLog:true,text:"[polyfill] sessionStorage 覆盖成功"},"*");}'
      'catch(e2){parent.postMessage({__thLog:true,text:"[polyfill] sessionStorage 覆盖失败: "+e2},"*");}'
      '}'
      // ── DOMContentLoaded 补火 ──
      '(function(){'
      'var _origAddEvt=document.addEventListener.bind(document);'
      'document.addEventListener=function(type,fn,opts){'
      'if(type==="DOMContentLoaded"&&document.readyState!=="loading"){setTimeout(fn,0);}'
      'else{_origAddEvt(type,fn,opts);}'
      '};'
      '})();'
      // ── console / onerror / unhandledrejection 转发日志 ──
      '(function(){'
      'var _log=function(level){return function(){'
      'try{var parts=[];for(var i=0;i<arguments.length;i++){var a=arguments[i];'
      'parts.push(typeof a==="object"?(function(){try{return JSON.stringify(a);}catch(e){return String(a);}})():String(a));}'
      'parent.postMessage({__thLog:true,text:"[引擎房:"+level+"] "+parts.join(" ")},"*");}catch(e){}'
      '};};'
      'console.log=_log("log");console.error=_log("error");console.warn=_log("warn");console.info=_log("info");'
      'window.onerror=function(msg,src,line,col,err){'
      'try{parent.postMessage({__thLog:true,text:"[引擎房:onerror] "+msg+" @"+line+":"+col+(err&&err.stack?" | "+err.stack:"")},"*");}catch(e){}'
      'return false;};'
      'window.addEventListener("unhandledrejection",function(ev){'
      'try{parent.postMessage({__thLog:true,text:"[引擎房:promise未捕获] "+(ev.reason&&ev.reason.message||ev.reason)},"*");}catch(e){}'
      '});'
      '})();'
      // ── frameId(请求路由用) ──
      'var _id=${jsonEncode(frameId)};'
      // ── __thCall 通信桥(iframe → Dart 请求/响应) ──
      'var __thPending={};var __thId=1;'
      'function __thCall(method,args){'
      'return new Promise(function(resolve,reject){'
      'var rid=_id+"_"+(__thId++);'
      '__thPending[rid]={resolve:resolve,reject:reject};'
      'setTimeout(function(){if(__thPending[rid]){delete __thPending[rid];reject(new Error("th timeout: "+method));}},30000);'
      'parent.postMessage({__thRequest:true,frameId:_id,rid:rid,method:method,args:args},"*");'
      '});'
      '}'
      'window.addEventListener("message",function(e){'
      'var d=e.data;if(!d||!d.__thResponse)return;'
      'var p=__thPending[d.rid];if(!p)return;delete __thPending[d.rid];'
      'if(d.ok)p.resolve(d.result);else p.reject(new Error(d.error||"th failed"));'
      '});'
      // ── 收外层中继来的事件 → 触发 MVU 注册的 eventOn 回调(点火) ──
      'window.__chatMessages=window.__chatMessages||[];'
      'window.addEventListener("message",function(e){'
      'var d=e.data;if(!d||!d.__thEvent)return;'
      'try{'
      'if(d.__msgs){window.__chatMessages=d.__msgs;}'
      'if(!window.__probed){window.__probed=1;'
      'parent.postMessage({__thLog:true,text:"[探针] typeof _="+(typeof window._)+" throttle="+((window._&&typeof window._.throttle))},"*");'
      'if(window._&&window._.throttle){var _c=0;var _t=window._.throttle(function(){_c++;return "ran";},3000);var _rv=_t();parent.postMessage({__thLog:true,text:"[探针] throttle首调返回="+_rv+" 实际执行="+_c},"*");}}'
      'parent.postMessage({__thLog:true,text:"[转接器] 收到 "+d.type+" 桶内监听器数="+((_TH.__events[d.type]||[]).length)+" 镜像条数="+((window.__chatMessages||[]).length)},"*");'
      '_TH.eventEmit.apply(_TH,[d.type].concat(d.args||[]));'
      'parent.postMessage({__thLog:true,text:"[引擎房] 点火 "+d.type},"*");}'
      'catch(err){parent.postMessage({__thLog:true,text:"[引擎房] 点火失败 "+d.type+": "+err},"*");}'
      '});'
      // ── _TH 门面接口 ──
      'var _TH={};'
      'window._TH=_TH;'
      '_TH.getChatMessages=function(range,option){'
      'var _m=(window.__chatMessages||[]).slice();'
      'var _r;'
      'if(typeof range==="number"){'
      'var idx=range<0?_m.length+range:range;'
      'var one=_m[idx];'
      '_r=one?[one]:[];'
      '}else{_r=_m;}'
      'var _last=_r[_r.length-1]||{};'
      'parent.postMessage({__thLog:true,text:"[闸探针] range="+JSON.stringify(range)+" 取到name="+JSON.stringify(_last.name)+" name2="+JSON.stringify((window.SillyTavern&&window.SillyTavern.name2))+" is_user="+_last.is_user+" 返回条数="+_r.length},"*");'
      'return _r;'
      '};'
      '_TH.setChatMessage=function(content,index,option){return __thCall("setChatMessage",[content,index,option||{}]);};'
      '_TH.setChatMessages=function(msgs,option){return __thCall("setChatMessages",[msgs,option||{}]);};'
      '_TH.createChatMessages=function(msgs,option){return __thCall("createChatMessages",[msgs,option||{}]);};'
      '_TH.deleteChatMessages=function(ids,option){return __thCall("deleteChatMessages",[ids,option||{}]);};'
      '_TH.triggerSlash=function(cmd){return __thCall("triggerSlash",[cmd]);};'
      '_TH.setInput=function(t){return __thCall("setInput",[t]);};'
      // ── 变量镜像(同步读):MVU 的 getVariables/getLastMessageId 是同步调用 ──
      // 读走本地镜像,写走桥落库后回填镜像(见 updateVariablesWith / __varSync)
      '_TH.__lastMsgId=0;'
      '_TH.__primaryLorebook=null;'
      '_TH.__varCache={global:{},chat:{},message:{}};'
      // ── EJS 标准对象:与镜像同源,供 dist/index.js 的 externals import ──
      'window.extension_settings=window.extension_settings||{};'
      'window.extension_settings.variables=window.extension_settings.variables||{global:{}};'
      'window.chat_metadata=window.chat_metadata||{variables:{}};'
      'window.chat=window.chat||[];'
      // ── 收外层推来的真实变量 → 回填镜像(反向同步) ──
      'window.addEventListener("message",function(e){'
      'var d=e.data;if(!d||!d.__varSync)return;'
      'var t=d.type||"chat";'
      'if(t==="message"){_TH.__varCache.message[d.message_id]=d.data||{};}'
      'else{_TH.__varCache[t]=d.data||{};}'
      // 同源回填 EJS 标准对象(与镜像并存,MVU 读镜像/EJS 读标准对象)
      'if(t==="global"){window.extension_settings.variables.global=d.data||{};}'
      'else if(t==="chat"){window.chat_metadata.variables=d.data||{};}'
      'else if(t==="message"){'
      'var _mid=d.message_id;'
      'if(typeof _mid==="number"){'
      'window.chat[_mid]=window.chat[_mid]||{};'
      'window.chat[_mid].variables=window.chat[_mid].variables||[];'
      'var _sw=(typeof d.swipe_id==="number")?d.swipe_id:0;'
      'window.chat[_mid].swipe_id=_sw;'
      'window.chat[_mid].variables[_sw]=d.data||{};'
      '}}'
      'if(typeof d.lastMsgId==="number")_TH.__lastMsgId=d.lastMsgId;'
      'parent.postMessage({__thLog:true,text:"[引擎房] 变量同步 "+t},"*");'
      '});'                                                              // ← 新增：闭合监听器①
      // ── 收外层推来的主世界书名 → 回填镜像 ──
      'window.addEventListener("message",function(e){'
      'var d=e.data;if(!d||!d.__primaryLorebookSync)return;'
      '_TH.__primaryLorebook=(typeof d.name==="string")?d.name:null;'
      'parent.postMessage({__thLog:true,text:"[引擎房] 主世界书同步 "+_TH.__primaryLorebook},"*");'
      '});'
      '_TH.getCurrentMessageId=function(){return (window.__chatMessages||[]).length-1;};'
      '_TH.getLastMessageId=function(){return (window.__chatMessages||[]).length-1;};'
      'window.getLastMessageId=function(){return (window.__chatMessages||[]).length-1;};'
      '_TH.getVariables=function(option){'
      'option=option||{};var t=option.type||"chat";'
      'if(t==="message"){'
      'var mid=option.message_id;'
      'if(mid===undefined||mid==="latest")mid=_TH.__lastMsgId;'
      'if(typeof mid==="number"&&mid<0)mid=_TH.__lastMsgId+1+mid;'
      'return _TH.__varCache.message[mid]||{};'
      '}'
      'return _TH.__varCache[t]||{};'
      '};'
      '_TH.setVariables=function(vars,option){return __thCall("setVariables",[vars,option||{}]);};'
      '_TH.replaceVariables=function(vars,option){return __thCall("replaceVariables",[vars,option||{}]);};'
      // ── 写接口(异步落库):MVU 的写操作都 await ──
      // updater 是 MVU 传入的函数,不能过桥,必须在 iframe 内跑;新值(纯数据)才过桥落库
      '_TH.__resolveMid=function(option){'
      'var mid=option.message_id;'
      'if(mid===undefined||mid==="latest")mid=_TH.__lastMsgId;'
      'if(typeof mid==="number"&&mid<0)mid=_TH.__lastMsgId+1+mid;'
      'return mid;'
      '};'
      '_TH.updateVariablesWith=function(updater,option){'
      'option=option||{};var t=option.type||"chat";'
      'var mid=(t==="message")?_TH.__resolveMid(option):null;'
      'var cur=(t==="message")?(_TH.__varCache.message[mid]||{}):(_TH.__varCache[t]||{});'
      'return Promise.resolve(updater(cur)).then(function(next){'
      'if(next===undefined)next=cur;'
      'if(t==="message"){_TH.__varCache.message[mid]=next;}else{_TH.__varCache[t]=next;}'
      'return __thCall("setVariables",[next,option]).then(function(){return next;});'
      '});'
      '};'
      '_TH.insertOrAssignVariables=function(vars,option){'
      'return _TH.updateVariablesWith(function(data){return Object.assign(data||{},vars);},option);'
      '};'
      'window.updateVariablesWith=_TH.updateVariablesWith;'
      'window.insertOrAssignVariables=_TH.insertOrAssignVariables;'
      '_TH.getAllVariables=function(){return __thCall("getAllVariables",[]);};'
      '_TH.getTavernHelperVersion=function(){return "4.9.1";};'
      // MVU 启动依赖:唯一脚本机制(假对象)
      '_TH.getScriptId=function(){parent.postMessage({__thLog:true,text:"[身份] getScriptId被调"},"*");return "kirakira-mvu-0";};'
      'window.getScriptId=_TH.getScriptId;'
      '_TH.registerAsUniqueScript=function(id){'
      'parent.postMessage({__thLog:true,text:"[身份] registerAsUniqueScript被调 id="+id},"*");'
      'return {listenPreferenceState:function(cb){parent.postMessage({__thLog:true,text:"[身份] listenPreferenceState注册,即将回调"},"*");try{cb("kirakira-mvu-0");}catch(e){parent.postMessage({__thLog:true,text:"[身份] cb异常"+e},"*");}return {stop:function(){}};}};};'
      'window.registerAsUniqueScript=_TH.registerAsUniqueScript;'
      // MVU 启动依赖:generate 空桩(真实现押后)
      '_TH.generate=function(cfg){parent.postMessage({__thLog:true,text:"[stub] generate 空桩"},"*");return Promise.resolve("");};'
      'window.generate=_TH.generate;'
      '_TH.generateRaw=function(cfg){parent.postMessage({__thLog:true,text:"[额外模型] generateRaw被调 hasCustomApi="+(!!(cfg&&cfg.custom_api))+" prompts="+((cfg&&cfg.ordered_prompts||[]).length)+" injects="+((cfg&&cfg.injects||[]).length)},"*");return __thCall("generateRaw",[cfg]);};'
      'window.generateRaw=_TH.generateRaw;'
      // substitudeMacros:同步宏替换(读宿主注入的 window.__KIRA_MACRO_VALUES)
      '_TH.substitudeMacros=function(t){'
      'if(typeof t!=="string")return t;'
      'var v=window.__KIRA_MACRO_VALUES||{user:"User",char:"Assistant"};'
      'return t.replace(/\\{\\{user\\}\\}/gi,v.user)'
      '.replace(/\\{\\{char\\}\\}/gi,v.char)'
      '.replace(/<user>/gi,v.user)'
      '.replace(/<char>/gi,v.char);'
      '};'
      'window.substitudeMacros=_TH.substitudeMacros;'
      // 世界书接口
      '_TH.getLorebookEntries=function(name){return __thCall("getLorebookEntries",[name]);};'
      '_TH.getCurrentCharPrimaryLorebook=function(){return _TH.__primaryLorebook;};'
      'window.getCurrentCharPrimaryLorebook=_TH.getCurrentCharPrimaryLorebook;'
      '_TH.getEnabledLorebookList=function(){return __thCall("getEnabledLorebookList",[]);};'
      'window.getEnabledLorebookList=_TH.getEnabledLorebookList;'
      '_TH.setLorebookEntries=function(name,entries){return __thCall("setLorebookEntries",[name,entries||[]]);};'
      '_TH.createLorebookEntry=function(name,entry){return __thCall("createLorebookEntry",[name,entry||{}]);};'
      '_TH.deleteLorebookEntries=function(name,uids){return __thCall("deleteLorebookEntries",[name,uids||[]]);};'
      '_TH.getCharacterLorebooks=function(){return __thCall("getCharacterLorebooks",[]);};'
      '_TH.getCharacterLorebooks=function(){return __thCall("getCharacterLorebooks",[]);};'
      'window.getCharacterLorebooks=_TH.getCharacterLorebooks;'  // MVU若喊长名
      '_TH.getCharLorebooks=_TH.getCharacterLorebooks;'          // MVU实际喊的短名
      'window.getCharLorebooks=_TH.getCharacterLorebooks;'       // 裸挂，让MVU够得着
      '_TH.getLorebooks=function(){return __thCall("getLorebooks",[]);};'
      '_TH.getLorebookSettings=function(){return {selected_global_lorebooks:[]};};'
      'window.getLorebookSettings=_TH.getLorebookSettings;'
      '_TH.setLorebookSettings=function(s){return true;};'
      'window.setLorebookSettings=_TH.setLorebookSettings;'
      '_TH.createLorebook=function(name){return __thCall("createLorebook",[name]);};'
      // ── 事件总线(iframe 本地实现) ──
      '_TH.__events={};'
      '_TH.__eventOn=function(type,listener){(_TH.__events[type]=_TH.__events[type]||[]).push(listener);return {stop:function(){_TH.__eventRemove(type,listener);}};};'
'_TH.eventOn=function(type,listener){var r=_TH.__eventOn(type,listener);if(type&&type.indexOf("th_unique_check.")===0){try{parent.postMessage({__thLog:true,text:"[选主] th_unique_check 立即回调 kirakira-mvu-0"},"*");listener("kirakira-mvu-0");}catch(e){parent.postMessage({__thLog:true,text:"[选主] 回调异常"+e},"*");}}return r;};'
      '_TH.eventMakeLast=function(type,listener){return _TH.__eventOn(type,listener);};'
      '_TH.eventMakeFirst=function(type,listener){var l=_TH.__events[type]=_TH.__events[type]||[];l.unshift(listener);return {stop:function(){_TH.__eventRemove(type,listener);}};};'
      '_TH.eventOnce=function(type,listener){var wrap=function(){_TH.__eventRemove(type,wrap);return listener.apply(this,arguments);};return _TH.__eventOn(type,wrap);};'
      '_TH.eventRemoveListener=function(type,listener){_TH.__eventRemove(type,listener);};'
      '_TH.__eventRemove=function(type,listener){var l=_TH.__events[type];if(!l)return;var i=l.indexOf(listener);if(i>=0)l.splice(i,1);};'
      '_TH.eventClearAll=function(){_TH.__events={};};'
      '_TH.eventEmit=function(type){var args=Array.prototype.slice.call(arguments,1);if(type&&type.indexOf("th_unique_check.")===0){args=["kirakira-mvu-0"];parent.postMessage({__thLog:true,text:"[选主] eventEmit 强制 th_unique_check=kirakira-mvu-0"},"*");}var l=(_TH.__events[type]||[]).slice();for(var i=0;i<l.length;i++){try{parent.postMessage({__thLog:true,text:"[emit] "+type+" 调listener#"+i},"*");var _r=l[i].apply(null,args);parent.postMessage({__thLog:true,text:"[emit] "+type+" listener#"+i+" 返回="+(_r&&typeof _r.then==="function"?"promise":typeof _r)},"*");if(_r&&typeof _r.then==="function"){_r.catch(function(e){parent.postMessage({__thLog:true,text:"[事件异步错误]"+type+": "+((e&&e.stack)||e)},"*");});}}catch(e){parent.postMessage({__thLog:true,text:"[事件同步错误]"+type+": "+((e&&e.stack)||e)},"*");}}};'
      '_TH.eventEmitAndWait=function(type){var args=Array.prototype.slice.call(arguments,1);var l=(_TH.__events[type]||[]).slice();var results=[];for(var i=0;i<l.length;i++){try{results.push(l[i].apply(null,args));}catch(e){console.error("[事件]"+type,e);}}return Promise.all(results);};'
      // tavern_events / iframe_events 常量表
      'window.tavern_events={'
      'MESSAGE_RECEIVED:"message_received",MESSAGE_UPDATED:"message_updated",MESSAGE_SWIPED:"message_swiped",MESSAGE_DELETED:"message_deleted",MORE_MESSAGES_LOADED:"more_messages_loaded",CHAT_CHANGED:"chat_changed",CHARACTER_MESSAGE_RENDERED:"character_message_rendered",USER_MESSAGE_RENDERED:"user_message_rendered",GENERATION_AFTER_COMMANDS:"generation_after_commands",GENERATION_STARTED:"generation_started",GENERATION_STOPPED:"generation_stopped",GENERATION_ENDED:"generation_ended",STREAM_TOKEN_RECEIVED:"stream_token_received",CONNECTED:"connected",DISCONNECTED:"disconnected",EXTENSION_SETTINGS_LOADED:"extension_settings_loaded",CHARACTER_SELECTED:"character_selected",CHARACTER_DELETED:"character_deleted",CHARACTER_RENAMED:"character_renamed",CHARACTER_CREATED:"character_created",CHAT_DELETED:"chat_deleted",GROUP_UPDATED:"group_updated",PRESET_RENAMED_BEFORE:"preset_renamed_before",MAIN_API_CHANGED:"main_api_changed",WORLDINFO_ENTRIES_LOADED:"worldinfo_entries_loaded",WORLDINFO_SCAN_DONE:"worldinfo_scan_done",CHAT_COMPLETION_PROMPT_READY:"chatcompletion_prompt_ready",CHAT_COMPLETION_SETTINGS_READY:"chatcompletion_settings_ready",GENERATE_AFTER_DATA:"generate_after_data",APP_READY:"app_ready",MESSAGE_SENT:"message_sent",MESSAGE_SWIPE_DELETED:"message_swipe_deleted",SETTINGS_LOADED:"settings_loaded",SETTINGS_UPDATED:"settings_updated",WORLDINFO_FORCE_ACTIVATE:"worldinfo_force_activate",WORLDINFO_UPDATED:"worldinfo_updated"'
      '};'
      'window.iframe_events={GENERATION_STARTED:"iframe_generation_started",GENERATION_ENDED:"iframe_generation_ended",STREAM_TOKEN_RECEIVED_FULLY:"iframe_stream_token_received_fully",STREAM_TOKEN_RECEIVED_INCREMENTALLY:"iframe_stream_token_received_incrementally"};'
      // 全部裸挂到 window
      'for(var _k in _TH){if(_TH.hasOwnProperty(_k)){window[_k]=_TH[_k];}}'
      'window.TavernHelper=_TH;'
      // clipboard polyfill
      '(function(){try{'
      'if(!navigator.clipboard){Object.defineProperty(navigator,"clipboard",{configurable:true,value:{}});}'
      'if(!navigator.clipboard.writeText){navigator.clipboard.writeText=function(t){'
      'try{if(window.setInput){window.setInput(String(t));}}catch(e){}'
      'return Promise.resolve();};}'
      'if(!navigator.clipboard.readText){navigator.clipboard.readText=function(){return Promise.resolve("");};}'
      '}catch(e){parent.postMessage({__thLog:true,text:"[polyfill] clipboard 失败: "+e},"*");}})();'
      // ── SillyTavern.getContext() 骨架 ──
      'var _ctx={'
      'eventSource:{'
      'on:function(t,l){return _TH.eventOn(t,l);},'
      'once:function(t,l){return _TH.eventOnce(t,l);},'
      'emit:function(t){var a=Array.prototype.slice.call(arguments,1);return _TH.eventEmit.apply(_TH,[t].concat(a));},'
      'removeListener:function(t,l){return _TH.eventRemoveListener(t,l);},'
      'makeLast:function(t,l){return _TH.eventMakeLast(t,l);},'
      'makeFirst:function(t,l){return _TH.eventMakeFirst(t,l);}'
      '},'
      'eventTypes:window.tavern_events,'
      'getChatMessages:function(r,o){return _TH.getChatMessages(r,o);},'
      'setChatMessage:function(c,i,o){return _TH.setChatMessage(c,i,o);},'
      'chat:[],characters:[],characterId:0,groupId:null,chatId:(window.__KIRA_CHAT_ID||""),'
      'chatMetadata:{},extensionSettings:{},name1:"You",name2:((window.__KIRA_MACRO_VALUES&&window.__KIRA_MACRO_VALUES.char)||""),'
      'saveChat:function(){return Promise.resolve();},'
      'saveMetadata:function(){return Promise.resolve();},'
      'reloadCurrentChat:function(){return Promise.resolve();},'
      'getRequestHeaders:function(){return {"Content-Type":"application/json"};},'
      'renderExtensionTemplateAsync:function(){return Promise.resolve("");}'
      '};'
      'window.SillyTavern={getContext:function(){return _ctx;},'
      'saveChat:function(){return Promise.resolve();},'
      'saveSettingsDebounced:function(){},'
      'getCurrentChatId:function(){return window.__KIRA_CHAT_ID||"";},'
      '__macros:{},'
      'registerMacro:function(k,fn){try{window.SillyTavern.__macros[k]=fn;}catch(e){}},'
      'unregisterMacro:function(k){try{delete window.SillyTavern.__macros[k];}catch(e){}},'
      'name1:"You",name2:((window.__KIRA_MACRO_VALUES&&window.__KIRA_MACRO_VALUES.char)||""),'
      'extensionSettings:{mvu_settings:{'
      '更新方式:${jsonEncode(mvu.updateMode)},'
      '额外模型解析配置:{'
      '破限方案:${jsonEncode(mvu.jailbreakScheme)},'
      '启用自动请求:${mvu.autoRequest},'
      'max_chat_history:${mvu.maxChatHistory},'
      '模型来源:${jsonEncode(mvu.modelSource)},'
      'api地址:${jsonEncode(mvu.apiUrl)},'
      '密钥:${jsonEncode(mvu.apiKey)},'
      '模型名称:${jsonEncode(mvu.modelName)}'
      '}}}'
      '};'
      'try{Object.defineProperty(window.SillyTavern,"chat",{configurable:true,get:function(){return window.__chatMessages||[];}});}catch(e){window.SillyTavern.chat=window.__chatMessages||[];}'
      'window.appendInexistentScriptButtons=function(){};'
      'window.getButtonEvent=function(n){return "button_event_"+n;};'
      'window.getScriptButtons=function(){return [];};'
      'window.getContext=function(){return _ctx;};'
      '})();';
}